### ISSUE TITLE
Re adding live chart links etc

### ISSUE THREAD

**Issue by Alchemi1** [halon176/h-crypto-price-bot#1]
Greetings, 
Really love what ya built here. 
Super clean and quality. 

Have you thought of adding live chart links for each token/coin etc? 

I think this would be a great addition. 

Just thought to mention. 

Thanks for the great work your doing... 

A*

**Comment by halon176** [comment]
Hello! First of all, thank you!

Yes, it's a feature that I will definitely add. I'm just evaluating the best way to do it. Coingecko's free API allows you to get chart data from more than 24 hours ago, so I was thinking of introducing a function like '/c coin' to show the chart with the ability to change the time frame. I don't think I'll include it in the general price view because the message would become too long.

I would like to find a solution for the chart of the last 24 hours, but for now I haven't found a valid one.
